package constants

const (
	ColumnDataTypeBoolean   = "boolean"
	ColumnDataTypeTinyInt   = "tinyint"
	ColumnDataTypeSmallInt  = "smallint"
	ColumnDataTypeInteger   = "integer"
	ColumnDataTypeBigInt    = "bigint"
	ColumnDataTypeUTinyInt  = "utinyint"
	ColumnDataTypeUSmallInt = "usmallint"
	ColumnDataTypeUInteger  = "uinteger"
	ColumnDataTypeUBigInt   = "ubigint"
	ColumnDataTypeFloat     = "float"
	ColumnDataTypeDouble    = "double"
	ColumnDataTypeVarchar   = "varchar"
	ColumnDataTypeTimestamp = "timestamp"
	ColumnDataTypeDate      = "date"
	ColumnDataTypeTime      = "time"
	ColumnDataTypeJson      = "json"
	ColumnDataTypeInterval  = "interval"
	ColumnDataTypeDecimal   = "decimal"
	ColumnDataTypeUUID      = "uuid"
	ColumnDataTypeBlob      = "blob"
	ColumnDataTypeStruct    = "struct"

	// array types
	ColumnDataTypeBooleanArray   = "boolean[]"
	ColumnDataTypeTinyIntArray   = "tinyint[]"
	ColumnDataTypeSmallIntArray  = "smallint[]"
	ColumnDataTypeIntegerArray   = "integer[]"
	ColumnDataTypeBigIntArray    = "bigint[]"
	ColumnDataTypeUTinyIntArray  = "utinyint[]"
	ColumnDataTypeUSmallIntArray = "usmallint[]"
	ColumnDataTypeUIntegerArray  = "uinteger[]"
	ColumnDataTypeUBigIntArray   = "ubigint[]"
	ColumnDataTypeFloatArray     = "float[]"
	ColumnDataTypeDoubleArray    = "double[]"
	ColumnDataTypeVarcharArray   = "varchar[]"
	ColumnDataTypeTimestampArray = "timestamp[]"
	ColumnDataTypeDateArray      = "date[]"
	ColumnDataTypeTimeArray      = "time[]"
	ColumnDataTypeJsonArray      = "json[]"
	ColumnDataTypeIntervalArray  = "interval[]"
	ColumnDataTypeDecimalArray   = "decimal[]"
	ColumnDataTypeUUIDArray      = "uuid[]"
	ColumnDataTypeBlobArray      = "blob[]"
	ColumnDataTypeStructArray    = "struct[]"
)
