package constants

const (
	DuckDbTypeBoolean   = "boolean"
	DuckDbTypeTinyInt   = "tinyint"
	DuckDbTypeSmallInt  = "smallint"
	DuckDbTypeInteger   = "integer"
	DuckDbTypeBigInt    = "bigint"
	DuckDbTypeUTinyInt  = "utinyint"
	DuckDbTypeUSmallInt = "usmallint"
	DuckDbTypeUInteger  = "uinteger"
	DuckDbTypeUBigInt   = "ubigint"
	DuckDbTypeFloat     = "float"
	DuckDbTypeDouble    = "double"
	DuckDbTypeVarchar   = "varchar"
	DuckDbTypeTimestamp = "timestamp"
	DuckDbTypeDate      = "date"
	DuckDbTypeTime      = "time"
	DuckDbTypeJson      = "json"
	DuckDbTypeInterval  = "interval"
	DuckDbTypeDecimal   = "decimal"
	DuckDbTypeUUID      = "uuid"
	DuckDbTypeBlob      = "blob"
	DuckDbTypeStruct    = "struct"

	// array types
	DuckDbTypeBooleanArray   = "boolean[]"
	DuckDbTypeTinyIntArray   = "tinyint[]"
	DuckDbTypeSmallIntArray  = "smallint[]"
	DuckDbTypeIntegerArray   = "integer[]"
	DuckDbTypeBigIntArray    = "bigint[]"
	DuckDbTypeUTinyIntArray  = "utinyint[]"
	DuckDbTypeUSmallIntArray = "usmallint[]"
	DuckDbTypeUIntegerArray  = "uinteger[]"
	DuckDbTypeUBigIntArray   = "ubigint[]"
	DuckDbTypeFloatArray     = "float[]"
	DuckDbTypeDoubleArray    = "double[]"
	DuckDbTypeVarcharArray   = "varchar[]"
	DuckDbTypeTimestampArray = "timestamp[]"
	DuckDbTypeDateArray      = "date[]"
	DuckDbTypeTimeArray      = "time[]"
	DuckDbTypeJsonArray      = "json[]"
	DuckDbTypeIntervalArray  = "interval[]"
	DuckDbTypeDecimalArray   = "decimal[]"
	DuckDbTypeUUIDArray      = "uuid[]"
	DuckDbTypeBlobArray      = "blob[]"
	CDuckDbTypeStructArray   = "struct[]"
)
