// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TailpipePlugin_GetSchema_FullMethodName   = "/proto.TailpipePlugin/GetSchema"
	TailpipePlugin_AddObserver_FullMethodName = "/proto.TailpipePlugin/AddObserver"
	TailpipePlugin_Collect_FullMethodName     = "/proto.TailpipePlugin/Collect"
)

// TailpipePluginClient is the client API for TailpipePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TailpipePluginClient interface {
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	AddObserver(ctx context.Context, in *AddObserverRequest, opts ...grpc.CallOption) (TailpipePlugin_AddObserverClient, error)
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Empty, error)
}

type tailpipePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewTailpipePluginClient(cc grpc.ClientConnInterface) TailpipePluginClient {
	return &tailpipePluginClient{cc}
}

func (c *tailpipePluginClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, TailpipePlugin_GetSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tailpipePluginClient) AddObserver(ctx context.Context, in *AddObserverRequest, opts ...grpc.CallOption) (TailpipePlugin_AddObserverClient, error) {
	stream, err := c.cc.NewStream(ctx, &TailpipePlugin_ServiceDesc.Streams[0], TailpipePlugin_AddObserver_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tailpipePluginAddObserverClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TailpipePlugin_AddObserverClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type tailpipePluginAddObserverClient struct {
	grpc.ClientStream
}

func (x *tailpipePluginAddObserverClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tailpipePluginClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TailpipePlugin_Collect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TailpipePluginServer is the server API for TailpipePlugin service.
// All implementations must embed UnimplementedTailpipePluginServer
// for forward compatibility
type TailpipePluginServer interface {
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	AddObserver(*AddObserverRequest, TailpipePlugin_AddObserverServer) error
	Collect(context.Context, *CollectRequest) (*Empty, error)
	mustEmbedUnimplementedTailpipePluginServer()
}

// UnimplementedTailpipePluginServer must be embedded to have forward compatible implementations.
type UnimplementedTailpipePluginServer struct {
}

func (UnimplementedTailpipePluginServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedTailpipePluginServer) AddObserver(*AddObserverRequest, TailpipePlugin_AddObserverServer) error {
	return status.Errorf(codes.Unimplemented, "method AddObserver not implemented")
}
func (UnimplementedTailpipePluginServer) Collect(context.Context, *CollectRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedTailpipePluginServer) mustEmbedUnimplementedTailpipePluginServer() {}

// UnsafeTailpipePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TailpipePluginServer will
// result in compilation errors.
type UnsafeTailpipePluginServer interface {
	mustEmbedUnimplementedTailpipePluginServer()
}

func RegisterTailpipePluginServer(s grpc.ServiceRegistrar, srv TailpipePluginServer) {
	s.RegisterService(&TailpipePlugin_ServiceDesc, srv)
}

func _TailpipePlugin_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TailpipePluginServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TailpipePlugin_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TailpipePluginServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TailpipePlugin_AddObserver_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AddObserverRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TailpipePluginServer).AddObserver(m, &tailpipePluginAddObserverServer{stream})
}

type TailpipePlugin_AddObserverServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type tailpipePluginAddObserverServer struct {
	grpc.ServerStream
}

func (x *tailpipePluginAddObserverServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _TailpipePlugin_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TailpipePluginServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TailpipePlugin_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TailpipePluginServer).Collect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TailpipePlugin_ServiceDesc is the grpc.ServiceDesc for TailpipePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TailpipePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TailpipePlugin",
	HandlerType: (*TailpipePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _TailpipePlugin_GetSchema_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _TailpipePlugin_Collect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddObserver",
			Handler:       _TailpipePlugin_AddObserver_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
