name: "11 - Test: Acceptance"
on:
  workflow_call:
  push:
    tags:
      - v*
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  TAILPIPE_UPDATE_CHECK: false
  SPIPETOOLS_TOKEN: ${{ secrets.SPIPETOOLS_TOKEN }}

jobs:
  goreleaser:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Pipe Fittings Components repository
        uses: actions/checkout@v4
        with:
          repository: turbot/pipe-fittings
          path: pipe-fittings
          ref: tp

      - name: Checkout Tailpipe plugin SDK repository
        uses: actions/checkout@v4
        with:
          repository: turbot/tailpipe-plugin-sdk
          path: tailpipe-plugin-sdk
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: develop

       # this is required, check golangci-lint-action docs
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: Run CLI Unit Tests
        run: |
          cd tailpipe-plugin-sdk
          go clean -testcache
          go test -timeout 30s ./... -test.v

# TODO - add SDK acceptance tests
